//
//  BreedsInteractor.swift
//  MadCollab
//
//  Created by Appineers India on 29/04/20.
//  Copyright (c) 2020 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BreedsBusinessLogic
{
    func getBreeds()
}

protocol BreedsDataStore
{
  //var name: String { get set }
}

class BreedsInteractor: BreedsBusinessLogic, BreedsDataStore
{
  var presenter: BreedsPresentationLogic?
  var worker: BreedsWorker?
  //var name: String = ""
  
  // MARK: Do something
    func getBreeds() {
        worker = BreedsWorker()
        worker?.getBreeds(completionHandler: { (response, message, success) in
            self.presenter?.presentGetBreedsResponse(response: response, message: message ?? "", successCode: success ?? "0")
        })
    }
}
