//
//  MyProfileInteractor.swift
//  WhiteLabelApp
//
//  Created by hb on 25/09/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Protocol for My profile API
protocol MyProfileBusinessLogic {
    
}

/// Data Store for MY Profile API
protocol MyProfileDataStore {
    
}

/// Class for My Profile Interactor API
class MyProfileInteractor: MyProfileBusinessLogic, MyProfileDataStore {
    /// Presentor Instance
    var presenter: MyProfilePresentationLogic?
    /// Worked Instance
    var worker: MyProfileWorker?
    
}
