//
//  BlockedUserPresenter.swift
//  Time2Beat
//
//  Created by Appineers India on 17/09/20.
//  Copyright (c) 2020 The Appineers. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BlockedUserPresentationLogic
{
  func presentBlockedUsersResponse(response: [Connection.ViewModel]?, message: String, successCode: String)
    func presentBlockUserResponse(message: String, successCode: String)
}

class BlockedUserPresenter: BlockedUserPresentationLogic
{
  weak var viewController: BlockedUserDisplayLogic?
  
  // MARK: Do something
  
  func presentBlockedUsersResponse(response: [Connection.ViewModel]?, message: String, successCode: String) {
    viewController?.didReceiveBlockedUsersResponse(response: response, message: message, successCode: successCode)
  }

    func presentBlockUserResponse(message: String, successCode: String) {
        viewController?.didReceiveBlockUserResponse(message: message, successCode: successCode)
    }
}
