//
//  HomeFilterPresenter.swift
//  MadCollab
//
//  Created by Appineers India on 08/05/20.
//  Copyright (c) 2020 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeFilterPresentationLogic
{
      func presentStateList(response: [StateList.ViewModel]?, message: String, successCode: String)
}

class HomeFilterPresenter: HomeFilterPresentationLogic
{
  weak var viewController: HomeFilterDisplayLogic?
  
  /// Present state list response
  ///
  /// - Parameters:
  ///   - response: API Response
  ///   - message: API  Message
  ///   - successCode: API Success
  func presentStateList(response: [StateList.ViewModel]?, message: String, successCode: String) {
      viewController?.didReceiveStateListResponse(response: response, message: message, successCode: successCode)
  }
}
