//
//  BreedsPresenter.swift
//  MadCollab
//
//  Created by Appineers India on 29/04/20.
//  Copyright (c) 2020 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BreedsPresentationLogic
{
    func presentGetBreedsResponse(response: [Breeds.ViewModel]?, message: String, successCode: String)
}

class BreedsPresenter: BreedsPresentationLogic
{
  weak var viewController: BreedsDisplayLogic?
  
  // MARK: Do something
  
    func presentGetBreedsResponse(response: [Breeds.ViewModel]?, message: String, successCode: String) {
          viewController?.didReceiveGetBreedsResponse(response: response, message: message, successCode: successCode)
    }
}
