//
//  ChatPresenter.swift
//  MadCollab
//
//  Created by Appineers India on 17/05/20.
//  Copyright (c) 2020 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChatPresentationLogic
{
    func presentSendMessageResponse(message: String, successCode: String)
    func presentDeleteMessageResponse(message: String, successCode: String)
}

class ChatPresenter: ChatPresentationLogic
{
  weak var viewController: ChatDisplayLogic?
  
  // MARK: Do something
    func presentSendMessageResponse(message: String, successCode: String) {
        viewController?.didReceiveSendMessageResponse(message: message, successCode: successCode)
    }
    
    func presentDeleteMessageResponse(message: String, successCode: String) {
          viewController?.didReceiveDeleteMessageResponse(message: message, successCode: successCode)
    }
}
