//
//  ChatWorker.swift
//  MadCollab
//
//  Created by Appineers India on 17/05/20.
//  Copyright (c) 2020 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ChatWorker
{
  func getChats(userId: String, completion: @escaping([Chat]) -> Void) {
   /* ChatAPI.getChats(userId: userId) {chats in
        completion(chats)
    }*/
  }
    
    func sendMessage(userId: String, firebaseId: String, message: String, completion: @escaping(Bool) -> Void) {
        /*ChatAPI.sendMessage(userId: userId, firebaseId: firebaseId, message: message) { response in
          completion(response)
        }*/
    }
    
    func setConnection(userId: String, type: String, completion: @escaping(Bool) -> Void) {
        /*ConnectionsAPI.setConnection(userId: userId, type: type) { response in
          completion(response)
        }*/
    }
    
    func reportUser(userId: String, message: String, completion: @escaping(Bool) -> Void) {
      /*ReportAPI.reportUser(userId: userId, message: message) { response in
          completion(response)
      }*/
    }
    
    func deleteMessage(chat: Chat, completion: @escaping(Bool) -> Void) {
        /*ChatAPI.deleteMessage(messageId: "0") {response in
          completion(response)
      }*/
    }
}
