//
//  ChatPresenter.swift
//  MadCollab
//
//  Created by Appineers India on 17/05/20.
//  Copyright (c) 2020 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChatPresentationLogic
{
    //func presentChats(response: [Chat])
    func presentSendMessageResponse(response: Bool)
    func presentSetConnectionResponse(response: Bool)
    func presentReportUserResponse(response: Bool)
    func presentDeleteMessageResponse(response: Bool)
}

class ChatPresenter: ChatPresentationLogic
{
  weak var viewController: ChatDisplayLogic?
  
  // MARK: Do something
 /* func presentChats(response: [Chat])
  {
      viewController?.displayChats(response: response)
  }*/
    
    func presentSendMessageResponse(response: Bool) {
        viewController?.displaySendMessageResponse(response: response)
    }
    
    func presentSetConnectionResponse(response: Bool) {
        viewController?.displaySetConnectionResponse(response: response)
    }

    func presentReportUserResponse(response: Bool) {
          viewController?.displayReportUserResponse(response: response)
    }
    
    func presentDeleteMessageResponse(response: Bool) {
      viewController?.displayDeleteMessageResponse(response: response)
    }
}
