//
//  PetProfilePresenter.swift
//  canoodle
//
//  Created by Appineers India on 20/10/20.
//  Copyright (c) 2020 The Appineers. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PetProfilePresentationLogic
{
  func presentSomething(response: PetProfile.Something.Response)
}

class PetProfilePresenter: PetProfilePresentationLogic
{
  weak var viewController: PetProfileDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: PetProfile.Something.Response)
  {
    let viewModel = PetProfile.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
