//
//  PetProfileInteractor.swift
//  canoodle
//
//  Created by Appineers India on 20/10/20.
//  Copyright (c) 2020 The Appineers. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PetProfileBusinessLogic
{
  func doSomething(request: PetProfile.Something.Request)
}

protocol PetProfileDataStore
{
  //var name: String { get set }
}

class PetProfileInteractor: PetProfileBusinessLogic, PetProfileDataStore
{
  var presenter: PetProfilePresentationLogic?
  var worker: PetProfileWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: PetProfile.Something.Request)
  {
    worker = PetProfileWorker()
    worker?.doSomeWork()
    
    let response = PetProfile.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
