//
//  PetProfilePresenter.swift
//  canoodle
//
//  Created by Appineers India on 20/10/20.
//  Copyright (c) 2020 The Appineers. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PetProfilePresentationLogic
{
    func presentUploadMediaResponse(message: String, success: String)
    func presentUpdatePetProfileResponse(message: String, success: String)
}

class PetProfilePresenter: PetProfilePresentationLogic
{
  weak var viewController: PetProfileDisplayLogic?
  
  // MARK: Do something
  
    func presentUploadMediaResponse(message: String, success: String) {
        viewController?.didReceiveUploadMediaResponse(message: message, success: success)
    }
    
    func presentUpdatePetProfileResponse(message: String, success: String) {
        viewController?.didReceiveUpdatePetProfileResponse(message: message, success: success)
    }
}
