//
//  UserProfilePresenter.swift
//  canoodle
//
//  Created by Appineers India on 15/10/20.
//  Copyright (c) 2020 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserProfilePresentationLogic
{
    func presentGetUserProfileResponse(response: [User.ViewModel]?, message: String, successCode: String)
}

class UserProfilePresenter: UserProfilePresentationLogic
{
  weak var viewController: UserProfileDisplayLogic?
  
  // MARK: Do something
  
    func presentGetUserProfileResponse(response: [User.ViewModel]?, message: String, successCode: String) {
      viewController?.didReceiveGetUserProfileResponse(response: response, message: message, successCode: successCode)
    }
}
