//
//  UserProfileInteractor.swift
//  canoodle
//
//  Created by Appineers India on 15/10/20.
//  Copyright (c) 2020 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserProfileBusinessLogic
{
    func getUserProfile(request: UserProfile.Request)
    func setConnection(request: SetConnection.Request)
    func reportUser(request: ReportUser.Request)
    func blockUser(request: BlockUser.Request)
}

protocol UserProfileDataStore
{
  //var name: String { get set }
}

class UserProfileInteractor: UserProfileBusinessLogic, UserProfileDataStore
{
  var presenter: UserProfilePresentationLogic?
  var worker: UserProfileWorker?
  //var name: String = ""
  
  // MARK: Do something
    func getUserProfile(request: UserProfile.Request) {
        worker = UserProfileWorker()
        worker?.getUserProfile(request: request, completionHandler: { (response, message, success) in
            self.presenter?.presentGetUserProfileResponse(response: response, message: message ?? "", successCode: success ?? "0")
        })
    }
    
    func setConnection(request: SetConnection.Request)
    {
      worker = UserProfileWorker()
      worker?.setConnection(request: request, completionHandler: { (message, success) in
          self.presenter?.presentSetConnectionResponse(message: message ?? "", successCode: success ?? "0")
      })
    }
    
    func reportUser(request: ReportUser.Request)
    {
      worker = UserProfileWorker()
      worker?.reportUser(request: request, completionHandler: { (message, success) in
          self.presenter?.presentReportUserResponse(message: message ?? "", successCode: success ?? "0")
      })
    }
    
    func blockUser(request: BlockUser.Request)
    {
      worker = UserProfileWorker()
      worker?.blockUser(request: request, completionHandler: { (message, success) in
          self.presenter?.presentBlockUserResponse(message: message ?? "", successCode: success ?? "0")
      })
    }
}
