//
//  ForgotPasswordPhoneRouter.swift
//  WhiteLabel
//
//  Created by hb on 09/09/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Protocol for forgot password phone routing
protocol ForgotPasswordPhoneRoutingLogic {
    func navigateToOtp(response: ForgotPasswordPhone.ViewModel?)
}

/// Protocol forgot password phone data passing
protocol ForgotPasswordPhoneDataPassing {
    var dataStore: ForgotPasswordPhoneDataStore? { get set }
}

/// Class for forgot password router
class ForgotPasswordPhoneRouter: NSObject, ForgotPasswordPhoneRoutingLogic, ForgotPasswordPhoneDataPassing {
    /// Viewcontroller instance
    weak var viewController: ForgotPasswordPhoneViewController?
    /// Datastore instance
    var dataStore: ForgotPasswordPhoneDataStore?
    
    /// Navigate to OTP
    ///
    /// - Parameter response: Response from API
    func navigateToOtp(response: ForgotPasswordPhone.ViewModel?) {
        if let otpVc = OTPVerificationViewController.instance() {
            otpVc.isFrom = "ForgotPassword"
            otpVc.phoneNumber = viewController?.txtFieldPhoneNumber.text?.getPhoneNumber() ?? ""
            otpVc.otp = response?.otp ?? ""
            otpVc.forgotPasswrdResponse = response
            self.viewController?.navigationController?.pushViewController(otpVc, animated: true)
        }
    }
}
