//
//  LoginPhoneInteractor.swift
//  WhiteLabel
//
//  Created by hb on 09/09/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Protocol for Login Phone API
protocol LoginPhoneBusinessLogic {
    func loginWithPhone(request: LoginPhoneModel.Request)
}

/// Protocol for Login Phone Data Store
protocol LoginPhoneDataStore {
    
}

/// Class for Login Phone Interactor
class LoginPhoneInteractor: LoginPhoneBusinessLogic, LoginPhoneDataStore {
    /// Presentor instance
    var presenter: LoginPhonePresentationLogic?
    /// Worker instance
    var worker: LoginPhoneWorker?
    
    /// Call Login with phone API
    ///
    /// - Parameter request: Login Phone Request
    func loginWithPhone(request: LoginPhoneModel.Request) {
        worker = LoginPhoneWorker()
        worker?.login(request: request, completionHandler: { (response, message, success) in
            self.presenter?.presentLoginResponse(response: response, message: message ?? "", success: success ?? "0")
        })
    }
}
