//
//  LoginPhonePresenter.swift
//  WhiteLabel
//
//  Created by hb on 09/09/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Protocol for login phone presentor
protocol LoginPhonePresentationLogic {
    /// Present login Response
    ///
    /// - Parameters:
    ///   - response: API Response
    ///   - message: API Message
    ///   - success: API Success
    func presentLoginResponse(response: Login.ViewModel?, message: String, success: String)
}

/// Class for login phone presentor
class LoginPhonePresenter: LoginPhonePresentationLogic {
    /// Viewcontroller for login email
    weak var viewController: LoginPhoneDisplayLogic?
    
    /// Present login Response
    ///
    /// - Parameters:
    ///   - response: API Response
    ///   - message: API Message
    ///   - success: API Success
    func presentLoginResponse(response: Login.ViewModel?, message: String, success: String) {
        self.viewController?.didReceiveLoginResponse(response: response, message: message, success: success)
    }
}
