//
//  CanoodleModels.swift
//  WhiteLabelApp
//
//  Created by hb on 25/09/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Canoodle Request and Response
enum Connection {
    struct Request {
        var connectionType : String
    }
    
    class ViewModel: WSResponseData {
        var userId : String?
        var userName : String?
        var userImage : String?
        
        private enum CodingKeys: String, CodingKey {
            case user_id
            case user_name
            case user_image
        }
        
        public override func encode(to encoder: Encoder) throws {
            try super.encode(to: encoder)
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(userId, forKey: .user_id)
            try container.encode(userName, forKey: .user_name)
            try container.encode(userImage, forKey: .user_image)
        }
        
        required public init(from decoder: Decoder) throws {
            try super.init(from: decoder)
            let values = try decoder.container(keyedBy: CodingKeys.self)
            userId = try values.decodeIfPresent(String.self, forKey: .user_id)
            userName = try values.decodeIfPresent(String.self, forKey: .user_name)
            userImage = try values.decodeIfPresent(String.self, forKey: .user_image)
        }
    }
}
