//
//  CanoodleWorker.swift
//  WhiteLabelApp
//
//  Created by hb on 25/09/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Class for Canoodle API Calls
class CanoodleWorker {
    /// Make API Calls
      func getConnections(request: Connection.Request, completionHandler: @escaping ([Connection.ViewModel]?, _ message: String?, _ successCode: String?) -> Void) {
          NetworkService.updateDataRequest(with: GetConnectionAPIRouter.getConnections(request: request), showHud: true) { (responce: WSResponse<Connection.ViewModel>?, error: NetworkError?) in
              if let detail = responce {
                  if let data = detail.arrayData, let success = detail.setting?.isSuccess, let msg = detail.setting?.message, success {
                      completionHandler(data, msg, detail.setting?.success)
                  } else {
                      completionHandler(nil, detail.setting?.message, detail.setting?.success)
                  }
              } else {
                  completionHandler(nil, error?.erroMessage() ?? AlertMessage.defaultError, "0")
              }
          }
      }
}
