//
//  CanoodlePresenter.swift
//  WhiteLabelApp
//
//  Created by hb on 25/09/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Canoodle Presentation
protocol CanoodlePresentationLogic {
    func presentGetConnectionsResponse(response: [Connection.ViewModel]?, message: String, successCode: String)
}

/// Canoodle Presentator
class CanoodlePresenter: CanoodlePresentationLogic {
    /// View Controller for Canoodle
    weak var viewController: CanoodleDisplayLogic?
    
    func presentGetConnectionsResponse(response: [Connection.ViewModel]?, message: String, successCode: String) {
      viewController?.didReceiveGetConnectionsResponse(response: response, message: message, successCode: successCode)
    }
}
