//
//  CanoodleRouter.swift
//  WhiteLabelApp
//
//  Created by hb on 25/09/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Protocol for Canoodle routing
protocol CanoodleRoutingLogic {
    
}

/// Protocol for Canoodle data passing
protocol CanoodleDataPassing {
    var dataStore: CanoodleDataStore? { get set }
}

/// Class for Canoodle router
class CanoodleRouter: NSObject, CanoodleRoutingLogic, CanoodleDataPassing {
    /// Viewcontroller instance
    weak var viewController: CanoodleViewController?
    /// Datastore instance
    var dataStore: CanoodleDataStore?
}
