//
//  CanoodleInteractor.swift
//  WhiteLabelApp
//
//  Created by hb on 25/09/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Protocol for Canoodle API
protocol CanoodleBusinessLogic {
    func getConnections(request: Connection.Request)
}

/// Protocol for Canoodle Data Store
protocol CanoodleDataStore {
    
}

/// Class for Canoodle Interactor
class CanoodleInteractor: CanoodleBusinessLogic, CanoodleDataStore {
    /// Presentor instance
   var presenter: CanoodlePresentationLogic?
    /// Worker instance
   var worker: CanoodleWorker?
    
    func getConnections(request: Connection.Request) {
        worker = CanoodleWorker()
        worker?.getConnections(request: request, completionHandler: { (response, message, success) in
            self.presenter?.presentGetConnectionsResponse(response: response, message: message ?? "", successCode: success ?? "0")
        })
    }
}
