//
//  MyProfilePresenter.swift
//  WhiteLabelApp
//
//  Created by hb on 25/09/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// My Profile Presenter
protocol MyProfilePresentationLogic {
    func presentGetUserProfileResponse(response: [User.ViewModel]?, message: String, successCode: String)
}

/// Presenter for my profile
class MyProfilePresenter: MyProfilePresentationLogic {
    /// Controller for my profile
    weak var viewController: MyProfileDisplayLogic?
    func presentGetUserProfileResponse(response: [User.ViewModel]?, message: String, successCode: String) {
      viewController?.didReceiveGetUserProfileResponse(response: response, message: message, successCode: successCode)
    }
}
