//
//  ForgotPasswordPhonePresenter.swift
//  WhiteLabel
//
//  Created by hb on 09/09/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Protocol for forgot password phone presentor
protocol ForgotPasswordPhonePresentationLogic {
    /// Present Forgot password Response
    ///
    /// - Parameters:
    ///   - message: API Message
    ///   - success: API Success
    func presentForgotPasswordResponse(response: ForgotPasswordPhone.ViewModel?, message: String, success: String)
}

/// Protocol for forgot password presentor
class ForgotPasswordPhonePresenter: ForgotPasswordPhonePresentationLogic {
    /// View controller for forgot password phone
    weak var viewController: ForgotPasswordPhoneDisplayLogic?
    
    /// Present Forgot password Response
    ///
    /// - Parameters:
    ///   - message: API Message
    ///   - success: API Success
    func presentForgotPasswordResponse(response: ForgotPasswordPhone.ViewModel?, message: String, success: String) {
        self.viewController?.didReceiveForgotPasswordResponse(response: response, message: message, success: success)
    }
}
