//
//  ForgotPasswordPhoneModels.swift
//  WhiteLabel
//
//  Created by hb on 09/09/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Forgot Password Request and Reponse
enum ForgotPasswordPhone {

   /// Reponse Class
    class ViewModel: WSResponseData {
        /// OTP Key
        var otp : String?
        /// Reset Key
        var resetKey: String?
        
        /// Enum for WS Response
        enum CodingKeys: String, CodingKey {
            /// - otp: OTP Param
            case otp
            /// - reset_key: Reset Key Param
            case reset_key
        }
        
        /// Init default method
        ///
        /// - Parameter decoder: Decoder
        /// - Throws: throws exception if found error
        required init(from decoder: Decoder) throws {
            try super.init(from: decoder)
            let values = try decoder.container(keyedBy: CodingKeys.self)
            otp = try values.decodeIfPresent(String.self, forKey: .otp)
            resetKey = try values.decodeIfPresent(String.self, forKey: .reset_key)
        }
        
        /// Default encode method
        ///
        /// - Parameter encoder: Encoder
        /// - Throws:throws exception if found error
        public override func encode(to encoder: Encoder) throws {
            try super.encode(to: encoder)
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(otp, forKey: .otp)
            try container.encode(resetKey, forKey: .reset_key)
        }
    }
}
