//
//  LikeViewController.swift
//  canoodle
//
//  Created by Appineers India on 12/10/20.
//  Copyright (c) 2020 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LikeDisplayLogic: class
{
    func didReceiveGetConnectionsResponse(response: [Connection.ViewModel]?, message: String, successCode: String)
}

class LikeViewController: BaseViewControllerWithAd
{
    @IBOutlet weak var viewAd: UIView!
    @IBOutlet weak var overlayView: UIView!
    @IBOutlet weak var likedButton: UIButton!
    @IBOutlet weak var likedMeButton: UIButton!
    @IBOutlet weak var connectionsTableView: UITableView!


   var interactor: LikeBusinessLogic?
   var router: (NSObjectProtocol & LikeRoutingLogic & LikeDataPassing)?
    
   var selectedSegmentIndex: Int = 0
    var connectionsList = [Connection.ViewModel]()

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
    
    // MARK: Class Instance
    class func instance() -> LikeViewController? {
        return StoryBoard.Like.board.instantiateViewController(withIdentifier: AppClass.LikeVC.rawValue) as? LikeViewController
    }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = LikeInteractor()
    let presenter = LikePresenter()
    let router = LikeRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    self.navigationItem.title = "Like"
    self.viewAd.isHidden = (UserDefaultsManager.getLoggedUserDetails()?.purchaseStatus?.booleanStatus() ?? false)
    likedButton.setShadow()
    likedButton.layer.borderColor = UIColor.white.cgColor
    likedButton.layer.borderWidth = 2.0
    likedButton.layer.cornerRadius = 5.0
    likedMeButton.setShadow()
    likedMeButton.layer.borderColor = UIColor.white.cgColor
    likedMeButton.layer.borderWidth = 2.0
    likedMeButton.layer.cornerRadius = 5.0
  }
    
    /// Method is called when view did appear
   override func viewDidAppear(_ animated: Bool) {
       super.viewDidAppear(animated)
       self.setAddMobView(viewAdd: self.viewAd)
       getConnections()
   }
  
    
    @IBAction func likedButtonTapped(_ sender: Any) {
        overlayView.removeFromSuperview()
        likedButton.setBackgroundImage(UIImage.init(named: "purpleRectBg"), for: UIControl.State.normal)
        likedMeButton.setBackgroundImage(UIImage.init(named: "greyRectBg"), for: UIControl.State.normal)
        selectedSegmentIndex = 0
    }
    
    @IBAction func likedMeButtonTapped(_ sender: Any) {
        overlayView.frame = CGRect(x: 0, y: self.view.frame.height - overlayView.frame.height, width: self.view.frame.width, height: overlayView.frame.height)
        self.view.addSubview(overlayView)
        likedButton.setBackgroundImage(UIImage.init(named: "greyRectBg"), for: UIControl.State.normal)
        likedMeButton.setBackgroundImage(UIImage.init(named: "purpleRectBg"), for: UIControl.State.normal)
        selectedSegmentIndex = 1
    }
    
  // MARK: Do something
  
  
    func getConnections() {
        let request = Connection.Request(connectionType: "Like")
        interactor?.getConnections(request: request)
    }
}

// UITableView Delegate methods
extension LikeViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return connectionsList.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        var cell: LikeViewCell! = tableView.dequeueReusableCell(withIdentifier: "LikeViewCell") as? LikeViewCell
        
        if cell == nil {
            tableView.register(UINib(nibName: "LikeViewCell", bundle: nil), forCellReuseIdentifier: "LikeViewCell")
            cell = tableView.dequeueReusableCell(withIdentifier: "LikeViewCell") as? LikeViewCell
        }
        //cell.delegate = self
        cell.setCellData(connection: connectionsList[indexPath.row], index: selectedSegmentIndex)
        return cell
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        if let userProfileVC = UserProfileViewController.instance() {
            let user: Connection.ViewModel = connectionsList[indexPath.row]
            userProfileVC.setUserId(userId: user.userId!)
            self.navigationController?.pushViewController(userProfileVC, animated: true)
        }
    }
}

extension LikeViewController: LikeDisplayLogic {
    func didReceiveGetConnectionsResponse(response: [Connection.ViewModel]?, message: String, successCode: String) {
        if successCode == "1" {
            print(message)
            if let data = response {
                connectionsList.removeAll()
                self.connectionsList.append(contentsOf: data)
                connectionsTableView.reloadData()
            }
        } else {
            //self.showTopMessage(message: message, type: .Error)
            connectionsList.removeAll()
            connectionsTableView.reloadData()
        }
    }
}

