//
//  LikeWorker.swift
//  canoodle
//
//  Created by Appineers India on 12/10/20.
//  Copyright (c) 2020 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LikeWorker
{
    func getConnections(request: Connection.Request, completionHandler: @escaping ([Connection.ViewModel]?, _ settings: WSResponseSetting?, _ message: String?, _ successCode: String?) -> Void) {
        GetNetworkService.dataRequest(with: GetConnectionAPIRouter.getConnections(request: request), showHud: true) { (responce: WSResponse<Connection.ViewModel>?, error: NetworkError?) in
            if let detail = responce {
                if let data = detail.arrayData, let success = detail.setting?.isSuccess, let settings = detail.setting, let msg = detail.setting?.message, success {
                    completionHandler(data, settings, msg, detail.setting?.success)
                } else {
                    completionHandler(nil, detail.setting ,detail.setting?.message, detail.setting?.success)
                }
            } else {
                completionHandler(nil, nil, error?.erroMessage() ?? AlertMessage.defaultError, "0")
            }
        }
    }
}
