//
//  FriendsRouter.swift
//  WhiteLabelApp
//
//  Created by hb on 25/09/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Protocol for friends routing
protocol FriendsRoutingLogic {
    
}

/// Protocol for friends data passing
protocol FriendsDataPassing {
    var dataStore: FriendsDataStore? { get set }
}

/// Class for friends router
class FriendsRouter: NSObject, FriendsRoutingLogic, FriendsDataPassing {
    /// Viewcontroller instance
    weak var viewController: FriendsViewController?
    /// Datastore instance
    var dataStore: FriendsDataStore?
}
