//
//  FriendsPresenter.swift
//  WhiteLabelApp
//
//  Created by hb on 25/09/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Friends Presentation
protocol FriendsPresentationLogic {
    
}

/// Friends Presentator
class FriendsPresenter: FriendsPresentationLogic {
    /// View Controller for Friends
    weak var viewController: FriendsDisplayLogic?
    
}
