//
//  OTPVerificationModels.swift
//  AppineersWhiteLabel
//
//  Created by hb on 04/09/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// OTP Verification Request and Reponse
enum OTPVerification {
  // MARK: Use cases
  
}
