//
//  OTPVerificationPresenter.swift
//  AppineersWhiteLabel
//
//  Created by hb on 04/09/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Protocol for OTP Verification
protocol OTPVerificationPresentationLogic {
    /// Present phone sign up Response
    ///
    /// - Parameters:
    ///   - response: API Response
    ///   - message: API Message
    ///   - success: API Success
    func presentPhoneSignUpResponse(response: [Login.ViewModel]?, message: String, successCode: String)
    /// Present unique user Response
    ///
    /// - Parameters:
    ///   - response: API Response
    ///   - message: API Message
    ///   - success: API Success
    func presentUniqeUser(response: [CheckUniqueUser.ViewModel]?, message: String, success: String)
    /// Present social sign up Response
    ///
    /// - Parameters:
    ///   - response: API Response
    ///   - message: API Message
    ///   - success: API Success
    func presentSocialSignUpResponse(response: [Login.ViewModel]?, message: String, successCode: String)
    /// Present forgot password Response
    ///
    /// - Parameters:
    ///   - response: API Response
    ///   - message: API Message
    ///   - success: API Success
    func presentForgotPasswordResponse(response: ForgotPasswordPhone.ViewModel?, message: String, success: String)
    /// Present change mobile number Response
    ///
    /// - Parameters:
    ///   - response: API Response
    ///   - message: API Message
    ///   - success: API Success
    func presentChangeMobileNumberResponse(message: String, success: String)
}

/// Class for OTP Verification
class OTPVerificationPresenter: OTPVerificationPresentationLogic {
    weak var viewController: OTPVerificationDisplayLogic?
    /// Present phone sign up Response
    ///
    /// - Parameters:
    ///   - response: API Response
    ///   - message: API Message
    ///   - success: API Success
    func presentPhoneSignUpResponse(response: [Login.ViewModel]?, message: String, successCode: String) {
        viewController?.didReceivePhoneSignUpResponse(viewModel: response, message: message, successCode: successCode)
    }
    /// Present unique user Response
    ///
    /// - Parameters:
    ///   - response: API Response
    ///   - message: API Message
    ///   - success: API Success
    func presentUniqeUser(response: [CheckUniqueUser.ViewModel]?, message: String, success: String) {
        self.viewController?.didReceiveUniqeUser(response: response, message: message, success: success)
    }
    /// Present social sign up Response
    ///
    /// - Parameters:
    ///   - response: API Response
    ///   - message: API Message
    ///   - success: API Success
    func presentSocialSignUpResponse(response: [Login.ViewModel]?, message: String, successCode: String) {
        viewController?.didReceiveSocialSignUpResponse(viewModel: response, message: message, successCode: successCode)
    }
    /// Present Response
    ///
    /// - Parameters:
    ///   - response: API Response
    ///   - message: API Message
    ///   - success: API Success
    func presentForgotPasswordResponse(response: ForgotPasswordPhone.ViewModel?, message: String, success: String) {
        self.viewController?.didReceiveForgotPasswordResponse(response: response, message: message, success: success)
    }
    /// Present change mobile number Response
    ///
    /// - Parameters:
    ///   - response: API Response
    ///   - message: API Message
    ///   - success: API Success
    func presentChangeMobileNumberResponse(message: String, success: String) {
        self.viewController?.didReceiveChangeMobileNumberResponse(message: message, success: success)
    }
}
