//
//  HomePresenter.swift
//  WhiteLabelApp
//
//  Created by hb on 18/09/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Home Presentor Protocol
protocol HomePresentationLogic {
  /// Present API Response
  ///
  /// - Parameter response: API Response
  func presentSomething(response: Home.Something.Response)
}

/// Home Presentor Class
class HomePresenter: HomePresentationLogic {
  /// Viewcontroller for home
  weak var viewController: HomeDisplayLogic?
  
  // MARK: Do something
  
    /// Present API Response
    ///
    /// - Parameter response: API Response
  func presentSomething(response: Home.Something.Response) {
    let viewModel = Home.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
