//
//  HomeModels.swift
//  WhiteLabelApp
//
//  Created by hb on 18/09/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

///Home Request and Reponse
enum Home {
  // MARK: Use cases
  
  enum Something {
    /// Struct for API Request
    struct Request {
    }
    /// Response
    struct Response {
    }
    /// ViewModel
    struct ViewModel {
    }
  }
}
