//
//  AboutMeWorker.swift
//  MadCollab
//
//  Created by Appineers India on 07/09/20.
//  Copyright (c) 2020 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class AboutMeWorker
{
    func updateProfile(request: UpdateProfile.Request, completionHandler: @escaping ( _ message: String?, _ successCode: String?) -> Void) {
        NetworkService.dataRequest(with: UpdateProfileAPIRouter.updateProfile(request: request)) { (responce: WSResponse<UpdateProfile.Response>?, error: NetworkError?) in
            if let detail = responce {
                if  detail.arrayData != nil, let success = detail.setting?.isSuccess, let msg = detail.setting?.message, success {
                    completionHandler( msg, detail.setting?.success)
                } else {
                    completionHandler(detail.setting?.message, detail.setting?.success)
                }
            } else {
                completionHandler(error?.erroMessage() ?? AlertMessage.defaultError, "0")
            }
        }
    }
}
