//
//  AboutMePresenter.swift
//  MadCollab
//
//  Created by Appineers India on 07/09/20.
//  Copyright (c) 2020 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AboutMePresentationLogic
{
}

class AboutMePresenter: AboutMePresentationLogic
{
  weak var viewController: AboutMeDisplayLogic?
  
  // MARK: Do something

}
