//
//  ResetPasswordInteractor.swift
//  PickUpUser
//
//  Created by hb on 10/06/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Protocol for Reset Password API
protocol ResetPasswordBusinessLogic {
    /// Call Reset Password API
    ///
    /// - Parameter request: Reset Password request
    func resetPasswordPassword(request: ResetPassword.Request)
}

/// Protocol For Reset Password Data Store
protocol ResetPasswordDataStore {
    
}

/// Class for Reset Password interactor
class ResetPasswordInteractor: ResetPasswordBusinessLogic, ResetPasswordDataStore {
    
    /// Presentor instance
    var presenter: ResetPasswordPresentationLogic?
    /// Worker instance
    var worker: ResetPasswordWorker?
    
    /// Call Reset Password API
    ///
    /// - Parameter request: Reset Password request
    func resetPasswordPassword(request: ResetPassword.Request) {
        worker = ResetPasswordWorker()
        worker?.resetPassword(request: request, completionHandler: { (message, success) in
            self.presenter?.presentResetPassword(message: message ?? "", success: success ?? "0")
        })
    }
    
}
