//
//  MessagesRouter.swift
//  WhiteLabelApp
//
//  Created by hb on 25/09/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Protocol for messages routing
protocol MessagesRoutingLogic {
    
}

/// Protocol for messages data passing
protocol MessagesDataPassing {
    var dataStore: MessagesDataStore? { get set }
}

/// Class for messages router
class MessagesRouter: NSObject, MessagesRoutingLogic, MessagesDataPassing {
    /// View controller instancs
    weak var viewController: MessagesViewController?
    /// Datastore instance
    var dataStore: MessagesDataStore?
}
