//
//  MessagesWorker.swift
//  WhiteLabelApp
//
//  Created by hb on 25/09/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Class for messages worker
class MessagesWorker {
    func getMessages(completionHandler: @escaping ([Message.ViewModel]?, _ message: String?, _ successCode: String?) -> Void) {
        NetworkService.updateDataRequest(with: GetMessageAPIRouter.getMessages, showHud: true) { (responce: WSResponse<Message.ViewModel>?, error: NetworkError?) in
            if let detail = responce {
                if let data = detail.arrayData, let success = detail.setting?.isSuccess, let msg = detail.setting?.message, success {
                    completionHandler(data, msg, detail.setting?.success)
                } else {
                    completionHandler(nil, detail.setting?.message, detail.setting?.success)
                }
            } else {
                completionHandler(nil, error?.erroMessage() ?? AlertMessage.defaultError, "0")
            }
        }
    }
    
    func deleteMessage(request: DeleteMessage.Request, completionHandler: @escaping ( _ message: String?, _ successCode: String?) -> Void) {
      NetworkService.dataRequest(with: GetMessageAPIRouter.deleteMessage(request: request)) { (responce: WSResponse<DeleteMessage.Response>?, error: NetworkError?) in
          if let detail = responce {
              if  detail.arrayData != nil, let success = detail.setting?.isSuccess, let msg = detail.setting?.message, success {
                  completionHandler( msg, detail.setting?.success)
              } else {
                  completionHandler(detail.setting?.message, detail.setting?.success)
              }
          } else {
              completionHandler(error?.erroMessage(), "0")
          }
      }
    }
}
