//
//  MessagesPresenter.swift
//  WhiteLabelApp
//
//  Created by hb on 25/09/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Presentor for Messages
protocol MessagesPresentationLogic {
    func presentGetMessagesResponse(response: [Message.ViewModel]?, message: String, successCode: String)
    func presentDeleteMessageResponse(message: String, successCode: String)
}

/// Message Presnetor
class MessagesPresenter: MessagesPresentationLogic {
    /// Viewcontroller for Messages
    weak var viewController: MessagesDisplayLogic?
    
    
    func presentGetMessagesResponse(response: [Message.ViewModel]?, message: String, successCode: String) {
      viewController?.didReceiveGetMessagesResponse(response: response, message: message, successCode: successCode)
    }
    
    func presentDeleteMessageResponse(message: String, successCode: String) {
          viewController?.didReceiveDeleteMessageResponse(message: message, successCode: successCode)
    }
}
