//
//  ResetPasswordPresenter.swift
//  PickUpUser
//
//  Created by hb on 10/06/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Protocol for reset password presentor
protocol ResetPasswordPresentationLogic {
    /// Present Reset Password Response
    ///
    /// - Parameters:
    ///   - response: API Response
    ///   - message: API Message
    ///   - success: API Success
  func presentResetPassword(message: String, success: String)
}

/// Class for reset password presentor
class ResetPasswordPresenter: ResetPasswordPresentationLogic {
    
  /// View controller for reset password
  weak var viewController: ResetPasswordDisplayLogic?
  
    /// Present Reset Password Response
    ///
    /// - Parameters:
    ///   - response: API Response
    ///   - message: API Message
    ///   - success: API Success
    func presentResetPassword(message: String, success: String) {
        viewController?.didReceivecResetPasswordResponse(message: message, success: success)
    }
  
}
