//
//  ResetPasswordModels.swift
//  PickUpUser
//
//  Created by hb on 10/06/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Reset Password request and Response
enum ResetPassword {
    /// Struct for API Request
    struct Request {
        /// Mobile Number Param
        var mobileNumber: String
        /// New Password Param
        var newPassword: String
        /// Reset Key Param
        var resetKey: String
    }
    
   /// Reponse Class
    class ViewModel: WSResponseData {
        /// Default encode method
        ///
        /// - Parameter encoder: Encoder
        /// - Throws:throws exception if found error
        public override func encode(to encoder: Encoder) throws {
            try super.encode(to: encoder)
        }
        
        /// Default Init Method
        ///
        /// - Parameter decoder: Decoder
        /// - Throws: throws exception if found error
        required public init(from decoder: Decoder) throws {
            try super.init(from: decoder)
        }
    }
}
