//
//  LoginPhoneRouter.swift
//  WhiteLabel
//
//  Created by hb on 09/09/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Protocol for Login Phone routing
protocol LoginPhoneRoutingLogic {
    func redirectToHome()
}

/// Protocol for Login Phone data passing
protocol LoginPhoneDataPassing {
    var dataStore: LoginPhoneDataStore? { get set }
}

class LoginPhoneRouter: NSObject, LoginPhoneRoutingLogic, LoginPhoneDataPassing {
    /// Viewcontroller instance
    weak var viewController: LoginPhoneViewController?
    /// Datastore instance
    var dataStore: LoginPhoneDataStore?
    
    /// Redirect to home
    func redirectToHome() {
        
        let storyboard = UIStoryboard(name: "TabBar", bundle: nil)
        if let tab = storyboard.instantiateInitialViewController(), tab is TabbarController {
            AppConstants.appDelegate.window?.rootViewController = tab
        }
    }
}
