//
//  HomeInteractor.swift
//  WhiteLabelApp
//
//  Created by hb on 18/09/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Protocol for Home API Call
protocol HomeBusinessLogic {
    func getUsers(request: User.Request)
}

/// Protocol home Data datastore
protocol HomeDataStore {
    //var name: String { get set }
}

/// Class for home API interactor
class HomeInteractor: HomeBusinessLogic, HomeDataStore {
    /// Presentor instance
    var presenter: HomePresentationLogic?
    /// Worker instance
    var worker: HomeWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func getUsers(request: User.Request) {
        worker = HomeWorker()
        worker?.getUsers(request: request, completionHandler: { (response, message, success) in
            self.presenter?.presentGetUsersResponse(response: response, message: message ?? "", successCode: success ?? "0")
        })
    }
}
